### ISSUE TITLE
Script does not run in headless mode 

### ISSUE THREAD

**Issue by hdeluna** [fiji/dockerfiles#9]
Hi, I just started using ImageJ and Docker a little ago, I'm trying to run a script, but an error keeps popping up. This is my command 

*sudo docker run -it --rm fiji/fiji fiji-linux64 --headless --run /path/to/script.txt 'file=/path/to/image/IMG_8919.JPG output_path=/path'*

I also have the same file saved as a macro but the same error pops for both:

*java.lang.IllegalArgumentException: Could not handle HTTPS in public boolean install(java.lang.String path) in ij.plugin.PluginInstaller
	at net.imagej.patcher.CodeHacker.handleHTTPS(CodeHacker.java:1221)
	at net.imagej.patcher.LegacyExtensions.injectHooks(LegacyExtensions.java:286)
	at net.imagej.patcher.LegacyInjector.inject(LegacyInjector.java:308)
	at net.imagej.patcher.LegacyInjector.injectHooks(LegacyInjector.java:109)
	at net.imagej.patcher.LegacyEnvironment.initialize(LegacyEnvironment.java:101)
	at net.imagej.patcher.LegacyEnvironment.applyPatches(LegacyEnvironment.java:495)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:397)
	at net.imagej.patcher.LegacyInjector.preinit(LegacyInjector.java:376)
	at fiji.IJ1Patcher.run(IJ1Patcher.java:37)
	at net.imagej.launcher.ClassLauncher.patchIJ1(ClassLauncher.java:195)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:154)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:76)
Feb 14, 2019 2:49:43 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Unrecognized command: "/path/to/script.txt"
[ERROR] Skipping unsupported option -port7*

What could be causing this and how could I solve it?

Thank you :)

**Comment by ctrueden** [comment]
@hdeluna Sorry, this repository is not fully maintained right now. The person who created it left the project, and I don't really know much about how it works, so I cannot really support it. Pull requests are very welcome if you figure it out, though. At some point I do expect to dive into Docker more and update this repository, but do not have time in the near future.
